cross-localedef-native: workaround fix build with glibc 2.28 host GNU C Library
Copy function '_IO_fwide' from the iofwide.c file.
Rename structure '_IO__FILE' to '__FILE' (typedef in glibc).
Remove a lot of redundant code since the variable 'mode' is always 0 (hard valua at function call).

Error:
 argp-fmtstream.c:(.text+0x4d2): undefined reference to `_IO_fwide'
| /home/hains/openpli-oe-core/build/tmp/hosttools/ld: argp-fmtstream.c:(.text+0x525): undefined reference to `_IO_fwide'
| /home/hains/openpli-oe-core/build/tmp/hosttools/ld: argp-help.o: in function `argp_failure':
| argp-help.c:(.text+0x20b3): undefined reference to `_IO_fwide'

This patch can be removed with target glibc 2.28.